name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: docker build . --file Dockerfile
        
  dockle:
    needs: test
    name: Dockle validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - name: Build image
        run: |
          docker build --no-cache --force-rm -t dockle-ci-test:latest .
          docker image save dockle-ci-test:latest -o dockle-ci-test.tar
          chmod 666 dockle-ci-test.tar
      - name: Dockle image
        run:
          docker run -v ${{github.workspace}}/dockle-ci-test.tar:/tmp/dockle-ci-test.tar --rm goodwithtech/dockle:v0.2.4 -d --input /tmp/dockle-ci-test.tar
      - name: cleanup
        run: |
          docker image remove dockle-ci-test:latest
          rm ${{github.workspace}}/dockle-ci-test.tar
          
  dockerhub:
    needs: dockle
    name: Dockerhub publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
      - name: Get the latest tag
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
      - name: Build the tagged Docker image
        run: docker build . --file Dockerfile --tag rvflash/goup:${{steps.vars.outputs.tag}}
      - name: Push the tagged Docker image
        run: docker push rvflash/goup:${{steps.vars.outputs.tag}}
      - name: Build the latest Docker image
        run: docker build . --file Dockerfile --tag rvflash/goup:latest
      - name: Push the latest Docker image
        run: docker push rvflash/goup:latest